name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
category-template: '## $TITLE'

sort-by: 'title'
sort-direction: 'ascending'

categories:
  - title: 'Added'
    labels:
      - 'added'
  - title: 'Fixed'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Removed'
    labels:
      - 'removed'
  - title: 'Security'
    labels:
      - 'security'
      - 'security fix'
      - 'security vulnerability'
  - title: 'Machine translation'
    labels:
      - 'machine'

exclude-labels:
  - 'skip-changelog'
  - 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: patch

template: |
  ## Changed

  $CHANGES
