on:
    workflow_call:

jobs:
    check:
        runs-on: ubuntu-latest
        
        if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/main' }}

        name: Check

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Install dependencies
                run: composer update

            -   name: Check the code-style
                run: vendor/bin/pint --parallel --test 

    fix:
        runs-on: ubuntu-latest
        
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

        name: Fix

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Fix the code-style
                run: composer style

            -   name: Create a Pull Request
                uses: peter-evans/create-pull-request@v7
                with:
                    branch: projects/code-style
                    branch-suffix: random
                    delete-branch: true
                    title: "🦋 The code style has been fixed"
                    commit-message: 🦋 The code style has been fixed
                    body: The code style has been fixed
                    labels: code-style
