on:
    workflow_call:

jobs:
    check:
        runs-on: ubuntu-latest

        name: Accept

        steps:
            - uses: thehanimo/pr-title-checker@v1.4.3
              with:
                configuration_path: .github/title-checker.json
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                pass_on_octokit_error: false
