on:
    workflow_call:

jobs:
    check:
        runs-on: ubuntu-latest

        name: Accept

        steps:
            - uses: thehanimo/pr-title-checker@v1.4.3
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                pass_on_octokit_error: false
                remote_configuration_path: "https://raw.githubusercontent.com/Laravel-Lang/.github/refs/heads/main/.github/title-checker.json"
