on:
    workflow_call:

jobs:
    check:
        runs-on: ubuntu-latest

        name: Accept

        steps:
            - uses: thehanimo/pr-title-checker@v1.4.3
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                pass_on_octokit_error: false
                github_configuration_owner: Laravel-Lang
                github_configuration_repo: .github
                github_configuration_path: .github/title-checker.json
                github_configuration_ref: main
