name: Translate

on:
    workflow_call:

jobs:
    locale:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            max-parallel: 2
            matrix:
                locale: [ af, ak, am, ar, as, az, be, bg, bho, bm, bn, bs, ca, ceb, ckb, cs, cy, da, de, de_CH, doi, ee, el, eo, es, et, eu, fa, fi, fil, fr, fy, ga, gd, gl, gu, ha, haw, he, hi, hr, hu, hy, id, ig, is, it, ja, ka, kk, km, kn, ko, ku, ky, lb, lg, ln, lo, lt, lv, mai, mg, mi, mk, ml, mn, mni_Mtei, mr, ms, mt, my, nb, ne, nl, nn, om, or, pa, pl, ps, pt, pt_BR, qu, ro, ru, rw, sa, sd, si, sk, sl, sn, so, sq, sr_Cyrl, su, sv, sw, ta, te, tg, th, ti, tk, tl, tr, tt, ug, uk, ur, uz_Cyrl, vi, xh, yi, yo, zh_CN, zh_HK, zh_TW, zu ]
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction
                    composer global require dragon-code/codestyler

            -   name: Translate
                run: vendor/bin/lang translate --locale ${{ matrix.locale }}

            -   name: Code-Style
                run: codestyle

            -   name: Create a Pull Request
                uses: peter-evans/create-pull-request@v6
                with:
                    branch: projects/translate
                    branch-suffix: random
                    delete-branch: true
                    add-paths: locales/${{ matrix.locale }}/*
                    title: "[${{ matrix.locale }}]: Machine translation of missing values 🤖"
                    commit-message: 🤖 Machine translation of missing values
                    body: Translated values for ${{ matrix.locale }} 💪
                    labels: machine
